apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-analytics
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: supabase-analytics
    creationPolicy: Owner
  data:
    - secretKey: apiKey
      remoteRef:
        key: supabase-app-secrets
        property: SERVICE_ROLE_KEY
