apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-secrets
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: supabase-secrets   # name of the Kubernetes Secret created
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: supabase-app-secrets   # <-- name of your AWS Secrets Manager secret
