apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-jwt
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: supabase-jwt
    creationPolicy: Owner
  data:
    - secretKey: anonKey
      remoteRef:
        key: supabase-app-secrets
        property: ANON_KEY
    - secretKey: serviceKey
      remoteRef:
        key: supabase-app-secrets
        property: SERVICE_ROLE_KEY
    - secretKey: jwtSecret
      remoteRef:
        key: supabase-app-secrets
        property: JWT_SECRET
