name: Terraform CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  terraform:
    name: Terraform Validate & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: infra
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: infra
        run: terraform validate

      - name: TFLint
        uses: terraform-linters/tflint-action@v0.46.1
        with:
          args: --chdir infra

